---
title: "O4"
author: "Gruppe 1"
date: "11/29/2020"
output:
  html_document: default
editor_options:
  chunk_output_type: console
---
# Del 1
```{r Del 1, fig.height=6, fig.width=7, echo=TRUE, message=FALSE, warning=FALSE}
# Laste inn pakker
library(lme4)
library(readxl)
library(tidyverse)
library(broom)
library(lme4)
library(emmeans)
library(cowplot)
library(kableExtra)
library(flextable)

#### DEL 1

# Laste inn data
df <- read_excel("./data/ten_vs_thirty.xlsx", na = "NA")

# Klargjør data for legpress
legpress <- df %>%
  filter(exercise == "legpress", # Velger ut øvelsen legpress
         timepoint %in% c("pre", "mid", "post")) %>% # Velger ut timepoints
  mutate(timepoint = factor(timepoint,
                            levels = c("pre", "mid", "post")), # Endre rekkefølgen på timepoints
         group = factor(group,
                        levels = c("RM30", "RM10"))) %>%# Endre rekkefølgen på gruppene. Ønsker å kontrollere for RM30.
  filter(!is.na(load)) # Fjerner data uten verdier i load



# Lager en figur som viser endringene i styrke for hver forsøksperson i de to gruppene
leg.figur <- legpress %>%
  mutate(timepoint = factor(timepoint, levels = c("pre", "mid", "post"))) %>%
  ggplot(aes(timepoint, load, group = subject, color)) + # Velger akser og bestemmer farge etter grupper
  geom_line() + # Hver forsøksperson får en linje mellom timepoints
  labs(x = "Timepoint", y = "1RM (kg)") + # Endre akseetiketter
  theme_minimal() # Velger layout på figuren
# Figuren viser endringer i styrke hos forsøkspersonene uavhengig av gruppe



# Lager en mixed model
# Interessert i å sammenligne endringer de to gruppene fra pre-test til post-test
# En mixed model kan ta høyde for repeterte målinger ved å bruke forsøkspersonen som en "tilfeldig effekt"
# Hver forsøksperson blir sammenlignet mot deres egen "pretest" (intercept)
lmer1 <- lmer(load ~ timepoint * group + (1|subject), data = legpress)

# summary(lmer1) # Denne kan aktiveres for en oppsummering av modellen

## Beskrivelse av output fra modellen:
# (Intercept) er gjennomsnittet ved pre-test (10RM)
# timepointpost er forskjellen fra pre-test til post-test
# groupRM10 er forskjellen mellom gruppene (10RM og 30RM) ved pre-test
# timepointpost:groupRM10 er forskjellen mellom gruppene ved post-test

## Variablene vi er interesserte i
# Forskjellen mellom gruppene når vi har kontrollert for pre-test etter en treningsintervensjon
# 39kg forskjell mellom 10RM og 30RM etter intevernsjonen (post-test)



# Plot av residualene
plot(lmer1)
# Variansen i residualene er tilnærmet like stor som "rangen" fitted values, så dette er ok.



## Estimater fra modellen
# Estimert gjennomsnitt ved hvert timepoint i hver gruppe
est <- emmeans(lmer1, specs = ~ timepoint|group) # Spesifiserer hvilke gjennomsnitt som skal kalkuleres




## Plotter esimatene fra modellen (Estimert gjennomsnitt)
# Objectet "est" må konverteres til en data frame for å kunne plottes
est.figur <- est %>% # Lager et nytt objekt med utgangspunkt i gjennomsnittene fra est
  data.frame() %>%
  mutate(timepoint = factor(timepoint, levels = c("pre", "mid", "post"))) %>%
  ggplot(aes(timepoint, emmean, group = group, color = group)) + 
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), # Representerer konfidensintervallene (95% CI)
                position = position_dodge(width = 0.2), # Flytter errorbarene fra hverandre
                width = 0.1) + # Endrer bredden på errorbarene.
  geom_line(position = position_dodge(width = 0.2)) + # Flytter linjene fra hverandre
  geom_point(position = position_dodge(width = 0.2)) +
  labs(x = "Timepoint", y = "1RM (kg)") + # Endrer akseetiketter
  theme_minimal() # Endrer temaet til figuren
# Figur: Viser estimerte gjennomsnitt for hver gruppe ved timepoint pre og post




raw.est.figur <- est %>%
  # Estimatene fra modellen
  data.frame() %>%
  mutate(timepoint = factor(timepoint, levels = c("pre", "mid", "post"))) %>%
  ggplot(aes(timepoint, emmean, group = group, color = group)) +
  #legg til rå-dataene
  geom_line(data = legpress, aes(timepoint, load, group = subject, color = group),
            alpha = 0.4) + # Legg til gjennomsiktighet til linjene
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL),
                position = position_dodge(width = 0.2),
                width = 0.1) +
  geom_line(position = position_dodge(width = 0.2)) +
  geom_point(position = position_dodge(width = 0.2)) +
  labs(x = "", y = "1RM (kg)",
       color = "Gruppe", title = "Figur 4.3") + # Nye akseetiketter
  # Fjerner tekst og indikatorer på x-aksen fordi vi skal kombinere dette plottet med et annet, og bruke teksten og indikatorene fra det plottet
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank()) +
  theme_minimal()
# Figur: Endringer i styrke for hver forsøksperson og estimert gjennomsnitt i hver gruppe ved timepoint pre og post





# Lagrer konfidensintervallene
# Henter 95% konfindensintervall fra hver av koeffisientene
konfidensintervall <- confint(lmer1)

# Konfidensintervallet ved post inneholder ikke 0. Det vil si at vi har bevis mot nullhypotesen som sier at det ikke er noen forskjell mellom de to gruppene. Det er en forskjell.


# Lagrer regresjonskoeffisientene
# Henter estimatene fra interaksjonskoeffisientene fra modellen
koef <- summary(lmer1)$coef

koef



# Bruker cbind for å kombinere konfidensintervallene med koeffisientene.
sum1 <- cbind(koef, data.frame(konfidensintervall)[3:8, ])

# Lager en tabell ved hjelp av kable
koeftabell <- sum1 %>%
  mutate(coef = rownames(.), 
         coef = factor(coef, levels = c("(Intercept)",
                                        "timepointmid",
                                        "timepointpost",
                                        "groupRM10",
                                        "timepointmid:groupRM10",
                                        "timepointpost:groupRM10"), 
                       labels=c("Gj.sn. pre-test",
                                "Endring: pre - mid (10RM)",
                                "Endring: pre - post (10RM",
                                "Diff. 10RM - 30RM (Pre)",
                                "Diff. 10RM - 30RM (Mid)",
                                "Diff. 10RM - 30RM (Post)"))) %>% # Navn på koeffisientene
  select(coef, Estimate, `Std. Error`, `t value`, X2.5.., X97.5..) %>% # Rangerer variablene
  kable(col.names = c("Koeffisient", "Estimat", "Std. Error", "t-verdi", "CI 2,5%", "CI 97,5%"), # Navn på overskrifter
        digits = c(1,1,2,1,1), # Bestemmer antall desimaler
        caption = "Tabell 1: Estimater fra koeffisientene, standard error, t-statistikk, nedre og øvre
        konfidensintervall ved pre-test, mid og post-test i begge gruppene") %>%
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover"))
           
koeftabell


# Figur for å vise anbefalt intensitet for utvikling av styrke. 
# Estimatene for "timepointpost" og "timepointpost:groupRM10"

# Redusere dataene og plotte dem slik at de viser forskjellene på gruppene ved post-test.
est.diff.figur <- sum1 %>%
  mutate(koef = rownames (.)) %>%
  # Filtrerer variablene
  filter(koef %in% c("timepointmid:groupRM10","timepointpost:groupRM10")) %>%
  # Lager en "timepointvariabel" for å presentere legpress datasettet
  mutate(timepoint = gsub("timepoint", "", koef),
         timepoint = gsub(":groupRM10", "", timepoint)) %>%
  # Legger til en rad slik at pre-test er representert
  add_row(timepoint = "pre", koef = "pre") %>%
  # Fikser rekkefølgen til timepoint variabelen
  mutate(timepoint = factor(timepoint, levels = c("pre", "mid", "post"))) %>%
  # Lager plottet
  ggplot(aes(timepoint, Estimate)) +
  # Legger til en linje som indikerer 0 (horisontal)
  geom_hline(yintercept = 0, lty = 2) +
  # Legger til errorbar og punkter i plottet
  geom_errorbar(aes(ymin = X2.5.., ymax = X97.5..), width = 0.1) +
  geom_point(shape = 24, size = 3, fill = "white") +
  # Endrer titler og akseetiketter
  labs(x = "Timepoint", y = "Gj.sn. forskjell mellom gruppene (95% CI)",
       color = "Gruppe") +
  theme_minimal()



figur04 <- plot_grid(raw.est.figur, est.diff.figur, ncol = 1,
                     align = "v",
                     axis = "lr")
figur04
```

# Del 2
```{r Del 2, fig.height=6, fig.width=7, echo=TRUE, message=FALSE, warning=FALSE}
##### DEL 2

# Laster inn data fra datasettet
df2 <- read_csv("./data/strengthTests.csv", na = "NA")

# Forberederer dataene fra den isometriske testen
isom <- df2 %>% 
  filter(!is.na(load)) %>% # Fjerner NA fra "load"
  filter(exercise == "isom",           # Velger øvelsen isometrisk styrke
         timepoint %in% c("pre", "session1", "post")) %>%  # Velger timepointene vi vil ha med
  # Endre rekkefølgen på timepoint
  mutate(timepoint = factor(timepoint, 
                            levels = c("pre", "session1", "post")), 
     # Kombinerer pre og session 1 til en egen timepoint. Heretter blir "time" brukt for å justere for timepoint
         time = if_else(timepoint == "post", "post", "pre"),
         time = factor(time,
                       levels = c("pre", "post")),
         # Endrer rekkefølgen på gruppene (sammenligner 3 sett mot 1 sett)
         group = factor(group,
                        levels = c("single", "multiple"))) %>%
  mutate(group = factor(group, levels = c("single", "multiple"),
                        labels = c("1 sett", "3 sett")))



# Lager en figur som viser endringen til forsøkspersonene fra pre til post
isom.figur <- isom %>%
  ggplot(aes(time, load, group = subject, color = group)) + # Bestemmer aksene og farger etter gruppe
  geom_line() + # Each subject gets a line
  labs(x = "Timepoint", y = "Motstand (N)") +    # Endrer navn på aksene
  theme_minimal()                              # Velger layout på figuren


# Lager en mixed model
# Interessert i å sammenligne endringer i mellom de to gruppene fra pre-test til post-test
# En mixed model kan ta høyde for repeterte målinger ved å bruke forsøkspersonen som en "tilfeldig effekt"
# Hver forsøksperson blir sammenlignet mot deres egen "pretest"
lmer2 <- lmer(load ~ time * group + (1|subject), data = isom)

# summary(lmer2) # Denne kan aktiveres for en oppsummering av modellen

# Plot av residualene
plot(lmer2)
# Variansen i residualene er tilnærmet like stor som "rangen" fitted values, så dette er ok.

## Estimater fra modellen
# Estimert gjennomsnitt ved hvert timepoint i hver gruppe
est2 <- emmeans(lmer2, specs = ~ time|group) # Spesifiserer hvilke gjennomsnitt som skal kalkuleres




est.figur2 <- est2 %>% # Lager et nytt objekt med utgangspunkt i est2
  data.frame() %>% # Gjør om dataene til dataframe
  mutate(time = factor(time, levels = c("pre", "post"))) %>% # Sørger for at rekkefølgen på timepoint blir korrekt
  ggplot(aes(time, emmean, group = group, color = group)) + # Plotter dataene
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), # Legger til errorbar som representerer 95% CI
                position = position_dodge(width = 0.2), # Flytter errorbarene fra hverandre slik at de ikke dekker til hverandre
                width = 0.1) + # Bestemmer bredden på errorbarene
  geom_line(position = position_dodge(width = 0.2)) +
  geom_point(position = position_dodge(width = 0.2)) +
  labs(x = "Timepoint", y = "Isometrisk styrke (N)") + # Endrer akseetikettene
  theme_minimal() # Velger tema for figuren
# Figur: Estimert gjennomsnitt i hver gruppe ved pre- og post-test




raw.est.figur2 <- est2 %>% # Lager et nytt objekt med utgangspunkt i est2
  data.frame() %>%
  mutate(time = factor(time, levels = c("pre", "session1", "post"))) %>% # Velger rekkefølgen på timepoint
  ggplot(aes(time, emmean, group = group, color = group) ) + # Oppretter plottet
  
  # Legger til rådata fra datasettet
  geom_line(data = isom, aes(time, load, group = subject, color = group), 
            alpha = 0.4) + # Gjør linjene gjennomsiktige 
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), # Legger til errorbars og formatterer disse slik at de ikke ligger over hverandre
                position = position_dodge(width = 0.2), 
                width = 0.1) +
  geom_line(position = position_dodge(width = 0.2)) +
  geom_point(position = position_dodge(width = 0.2)) +
  labs(x = "", y = "Isometrisk styrke (N)", 
       color = "Gruppe", title = "Figur 4.7") + # Setter nye navn på aksene og "legenden"
  # Fjerner tekst og akseetiketter på x-aksen fordi den skal kombineres med en annen figur
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank()) +
  theme_minimal()
# Figure: Endringer i styrke for hver enkelt forsøksperson i tillegg til estimert gjennomsnitt for de to gruppene ved timepoint pre og post.



# Lagrer konfidensintervallene
# Henter 95% konfindensintervall fra koeffisientene
konfidensintervall2 <- confint(lmer2)

# Konfidensintervallet ved post inneholder ikke 0. Det vil si at vi har bevis mot nullhypotesen som sier at det ikke er noen forskjell mellom de to gruppene. Det er en forskjell.


# Lagrer regresjonskoeffisientene
# Henter estimatene fra interaksjonskoeffisientene fra modellen
koef2 <- summary(lmer2)$coef


# Binder sammen regresjonskoeffisientene og konfidensintervallene til et objekt
sum2 <- cbind(koef2, data.frame(konfidensintervall2)[3:6, ])


# Lager en tabell med outputten i regresjonsmodellen og konfidensintervallene
koeftabell2 <- sum2 %>%
  mutate(coef = rownames(.), 
         coef = factor(coef, levels = c("(Intercept)",
                                        "timepost",
                                        "group3 sett",
                                        "timepost:group3 sett"), 
                       labels=c("Gj.sn. pre-test (3 sett)",
                                "Endring: pre - post (3 sett)",
                                "Diff. 3 sett - 1 sett (pre)",
                                "Diff. 3 sett - 1 sett (post)"))) %>% # Navn på koeffisientene
  select(coef, Estimate, `Std. Error`, `t value`, X2.5.., X97.5..) %>% # Rangerer variablene
  kable(col.names = c("Koeffisient", "Estimat", "Std. Error", "t-verdi", "CI 2,5%", "CI 97,5%"), # Navn på overskrifter
        digits = c(1,1,2,1,1), # Bestemmer antall desimaler i tabellen
        caption = "Tabell 2: Estimater fra koeffisientene, standard error, t-statistikk, nedre og øvre
        konfidensintervall ved pre-test, økt 1 og post-test i begge gruppene") %>% # Overskrift på tabellen
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover")) # Gjør tabellen penere

koeftabell2 # Printer tabellen






est.diff.figur2 <- sum2 %>% # Lager en figur med utgangspunkt i sum2
  mutate(koef2 = rownames(.)) %>%
  # Filtrerer hvilke variabler som skal med
  filter(koef2 %in% c("timepost:group3 sett")) %>%
  # Lager en "timepoint" variabel som skal representere "isom"-datasettet.
  mutate(time = gsub("time", "", koef2), 
         time = gsub(":group3 sett", "", time)) %>%
  # Legger til en rad så timepoint "pre" er representert
  add_row(time = "pre", koef2 = "pre") %>%
  # Fikser rekkefølgen til timepoint-variablene
  mutate(time = factor(time, levels = c("pre", "post"))) %>%
  # Lager figuren
  ggplot(aes(time, Estimate)) + 
  # Legger til en linje som representerer 0-punktet
  geom_hline(yintercept = 0, lty = 2) +
  # Legger til errorbarer og punkter
  geom_errorbar(aes(ymin = X2.5.., ymax = X97.5..), width = 0.1) +
  geom_point(shape = 24, size = 3, fill = "white") +
  # Legger til akseetiketter og tittel på "legenden"
  labs(x = "Timepoint", y = "Gj.sn. forskjell mellom gruppene(95% CI)", 
       color = "Gruppe") + 
  theme_minimal()

# Figur: Gjennomsnittlig forskjell i 1 RM legpress ved post-test, sammenligner 3 sett mot 1 sett
# Svarer på hypotesen vår: 3 sett burde være anbefalt volum for å øke styrke


# Kombinerer begge figuren til en resultatfigur
# bruker "raw.est.figur2" and "est.diff.figur2"
figur2 <- plot_grid(raw.est.figur2, est.diff.figur2, ncol = 1, 
                     # Justerer slik at x-aksene matcher hverandre
                     align = "v", 
                     # Justerer slik at aksene matcher hverandre både på venstre og høyre side
                     axis = "lr")
figur2 # Printer figuren
# Figur 1: Endringer i styrke (3 sett)  hos hver enkelt forsøksperson og gjennomsnittlig endringer i gruppene ved timepoint pre, mid og post. Gjennomsnittlig forskjell mellom de to gruppene ved timepoint mid og post.

```

